language: java
services:
  - docker
cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"
env:
  global:
    - GCP_PROJECT_ID=pgr301-m99
    - IMAGE=gcr.io/pgr301-m99/exam
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - secure: KJPBGA495gytoQ+AKkaDJ7cjlr3i0fCAyrlEzvOMdL8B/Ii9Ijt9+OKR2x1ap4jSXAHifM1wW3Hrrs7ZEzWOJWRtzusMoIA6qGs5jVR5n7uhGZuCvupPC0VKAnIj0wb8aHzJg1DGAmutzZ7yB7IK+G2VhgJOJ7vRvUVYjj2TEIw9XsDmTMEUSivE7S+mxQW13hYzzMn5OnXxpDg4CUihCgKEarQ8Sscjz5bBJ/ebqRrlSNfRHqgTS+Jmo88qvCGAR7hPtNMt8dwNEd4Pe2VCqGnzxSkHcKNVrz0wsvboEQkR6FaT718GM4aHdYYHP3Zz3tURedhNwM5icSzM38rnQmveaPHuVX7beGHpAU04/QxTXzittghGseYamjZ0ETqkWD9UJXhnVblSwJu6b0cjU0Z5k/O5tYGJf2mDZKjlNTt4rTJ/OvFbX09BWUx4uG8muu6l/h+q/lBaeLYEiNmvSeRqcl5SJ46XGVXgpCdX5vQ4j0swAb7dRPSETx2IQf38cjJa9htL8Mko32EbuCNlnmSIZdZRlxx1JnV4CklL6m1BRfOFKBcEkUnR9IIbq/2WGd4E4pToGXYd7UairuudNVh0/o2jd6vNpmpoQJZb9H1PIWZn0Qbb2ujVeBoSWwIC3GCzHV3FAMAP3VxdLFVktdiLMRmVjvSL1z/3LYpO9cI=
    - secure: Lepxe/twFa4suO5URnoI6FWIvnQizm719ymxh+IVI4LRgIyEk3iyVSS/9OOTSMk7Xae64q3hkDc2vxKlirPkenh7dl0yP8HhsZ4XV/lCo/VGAPVNeNfFrwcPADtgWSwDYc9BYa+pdKY/QrCtsl11Xheiisjk/VKg7QAssmZNc8F/lggPHrRo/TdnotMVMUCFP9Ab1qNdmu8LNi6nd9MZrGWGV1vmoy7YuB2ZBaf5Cx1KRIh9pkR8PVdfF3+WU63n49WF6meIjcdUTDeECmRe2GWir9P1ZuV4hhcR2kPceu6NIIPwUdzTZ5nMN341XrGXWYQRZZ7PoIfnGPvxyCSa65I8PfroNL5AB4vpY0M7ews5BCrc8v0UsiWQ+Q7dSPA3YOesaG6bGZgCnd4uCUmqWnO8ijIpABolvMWri/XRrpJ5vN7DIM6bGKOcvRYDFTEfcUKrBfIsPjarPE7CUrbxpoZbgb0iIeZ8nkz5DET9K39QWYB1GD8DHBDhJgd5VXBL9+wgIucTceuYJDP3D9jIZZns1O6gE6BJ2AvPmPOAuNAVF4PyZsAqWEzjA3yh7q7n5sblxmGFc1oUOk8vrnrEFcKxwH8IpSggk9ISNAr5nitKV3kmHSVlHIipH2XUeBgVnfUosQ/eBhTRu53ouv0l9/FtxL22NF9dczv4/QxcbN4=
before_install:
  - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=google-key.json
  - gcloud auth configure-docker
  - gcloud config set project "${GCP_PROJECT_ID}"
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: main
