language: java
services:
- docker
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
env:
  global:
  - GCP_PROJECT_ID=terraform-292215
  - IMAGE=gcr.io/terraform-292215/exam-10009
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: jBVQBHnpzZKjJX2I+m/Tg9nCnQPXWEjDY09rqL2tsUSUtmFh1Hu7o+wiBILDDXiBwlyd0Foxz/ub/wLnQdPQyYFEP+yGgMC20JCQxMvUt4d2sH5JKoMZFWGYlS4Ay/uw2r4+BigFLHDrflxv+pORtuovBK4vNgtCk/NWtVaEMQX3ioafIiYBZtf3y7JACnFOeUwSqCMZOmZce8wAiH2b628jIzPq7thsrpIoCjaOt0R9ogkiP6T3V3JWQxHPDcPpZZ07o4O6lobY51WJDiZTF3Q1skWr3hRpwJ8IWJkyd5ys/HaHlN49iQ+vNxuA6oWgvfTgRhCp8Vmo/bQZcfbkI9EuoYxelWvkdyTW0lfx9mC75uzcTATzRmlHyw9NzpF6B7bLMKVnFp05uULnb6di5Eio80jgG5XjKaR1pq9JhccIWDX8VChQg64hsfyiDS9t/2fj9fXBpQk3ZE2maO7/gNUIcrXzpBR/m9EZZd0m0WiOKn26RIXSEIJOeh/a5CnzHm2uXr7XVa8QI7vv8WhF1beiBl8fa2kA0Iw+0A6mCetIz3eLehTgs8jPVkRrzFRkw9YQUm+VOU5ZKmcc6/mlfKoIstwrMimtUhtYcEKJ/Ty4FPRVjvBj1CYvRQysCRz3uUXw3mJGr4/MQSSm7qUO6SfebyCbClrnBnu0UBaEK+o=
  - secure: fVC8LIm0fdC6d2vwqa9rM/vXRB7n/urdz33XX/5DjjuWlmxT3AC4SpwYieHhqZdm/LPdA1F5zOStzWz2YP+AD2mNxsZxUDwvPIIVGnVWXoCD9bIaynbSBNFaDZyCGrQgmSTIurG+KsOlDfwfMfYIqkrw1mgwwsARERc9X/SvS9nO1U0UCzPBnqUXJSvazM8oSqbSe4a9kzj3uHSYZGHpl81SqKI1g9nc+4luVt/P3s7iXuCtJvTti7mGe8PvPyrf6kwkAZFOWIZcHfyxs8m13F1EkT7FucInxbPHmBO7/NU/krUnmLgF7H9W+arvOlRG72ETavS3sA3KjTsebWF6dP3leWzpejU/oVLTaYyk/ibhZUdQferwydFca+PHSVokOxAyIu+WEzO0LVbCvSoLqdONNReOVbl6fbdCfot0m/0jvhzzbGvQlsQIhc8A8/FI3HZce0PcuV70fmu5VOmsqR6EY5wj8r69Jhp1EU0s0xSJRFdSWet2JTW8oK/cmp2KLqPFWaenE9UwB+E4QsV6lOFiuFLx6eoeRmcA219y4e3cL1pNbgh/SxYGIjySCzJb92NsgxwDqk8+q6dQ2LFwwT+pRsw518Fo+qj7hmQZaC40KAQUCe+ppguCHPclpL/GhYsiQijwFahoa0i4hYOfnX6fJYsVMlAaMDjZNp8kPYQ=
  - secure: b6AN6vFUF8np9CuxpiCtdF7ffZGCQfEG9tA1Ere49d+SSYPH6IxPtBjOeCt5uZdEObuxuWS3fNE5gW7boZHbvvmjp1mRREQI9MzcaJolouuthW4zZ37vYj6PY5p8n7G1iSoo36mrwzVwLxHKAWfQzZOTVU6wqHYEKdIk9qaWjITNboCm0sACa/dv2zpsFYzZ1lx4+dY0gdlFGZK8EalfeKhfy1hTwillSz8zUq9BEHcjvppfQ/f6Pw2tNlks3BkWG6DAQh70V4T8FZ+V3wyyH+1UXooFKzRkPT5JmGLz4NK2fcO6uY6NgneSTU+80EVAJ8vHlzQhnxG4zNVfv7MA3FkMDFHfBlHR6lOvIVZ+0hpmVJUXLxuU3SLZ94a1W8mwoPsev+fSHHOXb/mMlpc1DvPnOz8L792m3k0trMsWDdaFWoDTPfUHFHtuyuR3xyetyLn4xkmeP0KuhUcNf2hRC/75dnv65Wh+XgaSN7gCrNXXUjxir7+zRjnk9tdPI+bKJs9jJssYDAgWAEpVtI0F69jvMjyLVa2Akx//3JKGKUyfcWQBwT+v1rNqSi6FV1S1KCKpqbAcXEyTyEaJt8dkNbyiHtD0Bz9TIAcVocwk/8RLCIyLpfgjaZg0szK4xK7lJcrJb8A3BoVzyZ6/7QTiJaklbrRUDkKHa1zRWcof2s8=
  - secure: mU5+mbzbqUcBGgB3LQTqus2G22D7H75oX26Rgm871PwvA2lp6mL09eadYxaADbhL9p6zIevHNFSP3qhsryEKX6aCtywqHp7gHETIgu23E7FLJ4j/+1EdXxYlI5ThCuaFza2rLbRLsaiOJOioxUPdtGazGgpAlMcW2CR40It9PQ4oD0mxNtlNLhX47NFAqZDhZlLRhZba4ZhIennSG8OleyH6fJYaVjomOEKSZfly0ienCH4isIJhCFPBAhnqT3dyjRsCxwMlCHAW4vOZmf8905Y4yzpPaj4HHgWpJ9ELBcdBODjyVLmCz6EB/q+smXkOtE+PRoBShP35IkQeQeN1eYy2it0Y7WsTgb5MsP2e2FODdatFzbrtUtDhlfyqqcP6uPdttZjzQOAQbKYeU16rfnu6pGgxA6qcATf944ZC90geikxN6xhCfaBsPiMGtqKJPpD1c37VznUSaVW6zFq1hTZQBo4xG15Y5atKIU3nrCnp9yYx1VazXjw7pY9+Cvj31c5aCJ3dXNphoGVQGZlMJWdI/AywbrHFsDUPb0ZjYU15yGAXTQ+tu6g1Hc5uJhDe9bwtccoDv+Ybgoy3Vsp2mxi4VKEA7ICiVLWflXyqlI4GwrADjdPWChpypyr9+oownm27W5Qy166I3yjsyXHV8FLrI7Zdruk017xPtQDxdfA=
before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
  -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: main
