server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: h2
    show-sql: false